library("callr")
library("bibtex")
library("metafor")
library("grid")
library("gridExtra")
library("lme4")
library("ggplot2")
source("R/build.R")
source("R/data_processing.R")
source("R/figures.R")
source("R/model.R")
source("R/plots.R")
source("R/utils.R")
dir.create("output", FALSE, TRUE)
dir.create("downloads", FALSE, TRUE)
library("remake")
make_script(file = "analysis.R")
library("downloader")
download_baad("downloads/baad.rds")
paper_bib <- read.bib("references/paper.bib")
meta_bib <- read.bib("references/metaanalyses.bib")
combined_bib <- merge_bib_files(meta_bib, paper_bib)
write.bib(combined_bib, file = "output/refs.bib")
AllData <- clean_raw_data("data/CompileData.csv")
CleanData <- standardise_data(AllData)
CompleteData <- build_complete_data(CleanData)
CompleteData_inter <- Build_intersp_complete_data(CleanData)
IdealData <- build_ideal_data(CompleteData)
CoordTable <- build_map_data(CleanData)
IdealData_rgr <- subset_growth(IdealData, "RGR")
IdealData_agr <- subset_growth(IdealData, "AbGR")
CompleteData_rgr <- subset_growth(CompleteData_inter, "RGR")
CompleteData_agr <- subset_growth(CompleteData_inter, "AbGR")
GCi <- list_by_trait(CompleteData_inter)
GIi <- list_by_trait(IdealData)
knitr::knit("ms_suppinfo.Rnw", "ms_suppinfo.tex")
GIrgr <- list_by_trait(IdealData_rgr)
GIagr <- list_by_trait(IdealData_agr)
GCrgr <- list_by_trait(CompleteData_rgr)
GCagr <- list_by_trait(CompleteData_agr)
pdf("output/Fig1.pdf", height = 3L, width = 4L)
figure_1(CleanData)
dev.off()
pdf("output/Fig2.pdf", height = 9L, width = 4L)
figure_2(CompleteData_inter)
dev.off()
pdf("output/Fig3.pdf", height = 6L, width = 5L)
figure_3(GIrgr)
dev.off()
pdf("output/Fig4.pdf", height = 6L, width = 5L)
figure_3.4(GCi, GCrgr, GCagr)
dev.off()
baad <- readRDS("downloads/baad.rds")
pdf("output/FigA1.pdf", height = 3L, width = 9L)
figure_A1(baad)
dev.off()
pdf("output/FigA2.pdf", height = 3L, width = 6L)
figure_A2(CoordTable)
dev.off()
pdf("output/FigA3.pdf", height = 6L, width = 6L)
figure_A3(GCi)
dev.off()
pdf("output/FigA4.pdf", height = 6L, width = 5L)
figure_A4(GIi, GIrgr, GIagr)
dev.off()
pdf("output/FigA6a.pdf")
figure_A6(GCi, "SLA", "WD", c("a", "b"))
dev.off()
pdf("output/FigA6b.pdf")
figure_A6(GCi, "Aarea", "Seedmass", c("c", "d"))
dev.off()
pdf("output/FigA6c.pdf")
figure_A6.2(GCi, "Hmax", "e")
dev.off()
pdf("output/FigA7.pdf")
figure_A7(GCi)
dev.off()
pdf("output/FigA8.pdf")
figure_A8(GCi)
dev.off()
pdf("output/FigA9.pdf")
figure_A9(GCi)
dev.off()
`RCi{1}` <- EffectSizeSum(CompleteData_inter)
RCi <- list_by_trait(`RCi{1}`)
`RIi{1}` <- EffectSizeSum(IdealData_rgr)
RIi <- list_by_trait(`RIi{1}`)
pdf("output/FigA5.pdf", height = 6L, width = 5L)
figure_A5(RIi, RCi)
dev.off()
latex_build("MS.tex", bibliography = "output/refs.bib", clean = TRUE)
